default_language_version:
    python: python3

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
        -   id: check-merge-conflict
        -   id: check-added-large-files
            args: ['--maxkb=30000']
        -   id: check-executables-have-shebangs
        -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 21.9b0
    hooks:
    - id: black
      language_version: python3.9
-   repo: local
    hooks:
    -   id: isort
        name: isort
        description: Automatically sort imports.
        entry: isort
        args: [
            "--recursive",
        ]
        language: python
        language_version: python3.9
        types: [python]
        require_serial: true
        additional_dependencies: [isort]
    -   id: pytest
        name: Run Pytest
        description: Run Python unit-tests
        entry: pytest
        language: python
        types: [python]
        language_version: python3.8
        require_serial: true
        stages: [push]
        additional_dependencies: [
            pytest,
            pytest-cov,
            pytest-mock
        ]

-   repo: https://github.com/commitizen-tools/commitizen
    rev: v2.18.1
    hooks:
    -   id: commitizen
        stages: [commit-msg]